"""Build a Nornir InitNornir-compatible inventory from the pyATS testbed.

Single source of truth: agent/testbed.yaml (generated by scripts/generate_testbed.py
from the spec). This module produces Nornir Host/Group objects so we don't have
to maintain two inventory files.

Usage:
    from automation.inventory import init_nornir
    nr = init_nornir(role="managed")  # or role=None for all
    nr.run(task=...)
"""

from __future__ import annotations

import os
from pathlib import Path

import yaml
from nornir.core import Nornir
from nornir.core.inventory import (
    ConnectionOptions,
    Defaults,
    Group,
    Groups,
    Host,
    Hosts,
    Inventory,
    ParentGroups,
)

from scripts.credentials import load_credentials

TESTBED_PATH = Path(__file__).parent.parent / "agent" / "testbed.yaml"

# Map pyATS os -> netmiko device_type used by nornir-netmiko
OS_TO_NETMIKO = {
    "eos": "arista_eos",
    "iosxe": "cisco_xe",
    "ios": "cisco_ios",
    "fortinet_fortios": "fortinet",
    "linux": "linux",
}


def _load_creds_into_env() -> None:
    """Populate credential env vars if not already set (for %ENV{} substitution)."""
    creds = load_credentials()
    for key, val in [
        ("DEVICE_USERNAME", creds.device_username),
        ("DEVICE_PASSWORD", creds.device_password),
        ("DEVICE_ENABLE_PASSWORD", creds.device_enable_password),
        ("FORTIGATE_USERNAME", creds.fortigate_username),
        ("FORTIGATE_PASSWORD", creds.fortigate_password),
    ]:
        if val:
            os.environ.setdefault(key, val)


def _resolve_env(value: str) -> str:
    """Resolve %ENV{NAME} references the pyATS testbed format uses."""
    if not isinstance(value, str):
        return value
    if value.startswith("%ENV{") and value.endswith("}"):
        return os.environ.get(value[5:-1], "")
    return value


def build_inventory(role_filter: str | None = None) -> Inventory:
    """Convert pyATS testbed YAML -> Nornir inventory.

    Args:
        role_filter: If set ("managed" / "observed" / "excluded"), only include
            devices with that agent_role in the testbed custom block. None = all.
    """
    _load_creds_into_env()
    raw = yaml.safe_load(TESTBED_PATH.read_text())

    tb_block = raw.get("testbed", {})
    default_creds = tb_block.get("credentials", {}).get("default", {})
    default_user = _resolve_env(default_creds.get("username", ""))
    default_pass = _resolve_env(default_creds.get("password", ""))
    enable_pass = _resolve_env(
        tb_block.get("credentials", {}).get("enable", {}).get("password", "")
    )

    hosts: dict[str, Host] = {}
    groups: dict[str, Group] = {}

    # Group per platform/os for shared connection settings
    for os_name in OS_TO_NETMIKO:
        groups[os_name] = Group(name=os_name)

    for name, dev in raw.get("devices", {}).items():
        custom = dev.get("custom", {})
        agent_role = custom.get("agent_role", "")
        if role_filter and agent_role != role_filter:
            continue

        os_name = dev.get("os", "linux")
        netmiko_type = OS_TO_NETMIKO.get(os_name, "linux")

        # Per-device creds override default (FortiGate)
        per_dev = dev.get("credentials", {}).get("default", {})
        username = _resolve_env(per_dev.get("username", default_user))
        password = _resolve_env(per_dev.get("password", default_pass))

        cli = dev.get("connections", {}).get("cli", {})
        ip = cli.get("ip", "")
        port = cli.get("port", 22)

        host = Host(
            name=name,
            hostname=ip,
            port=port,
            username=username,
            password=password,
            platform=netmiko_type,
            groups=ParentGroups([groups[os_name]]) if os_name in groups else ParentGroups(),
            data={
                "agent_role": agent_role,
                "spec_role": custom.get("spec_role", ""),
                "platform": custom.get("platform", ""),
                "os": os_name,
            },
            connection_options={
                "netmiko": ConnectionOptions(
                    extras={
                        "secret": enable_pass if os_name in ("iosxe", "ios") else None,
                        "fast_cli": False,
                    }
                ),
            },
        )
        hosts[name] = host

    return Inventory(
        hosts=Hosts(**hosts),
        groups=Groups(**groups),
        defaults=Defaults(),
    )


def init_nornir(role: str | None = "managed", num_workers: int = 10) -> Nornir:
    """Create a Nornir instance backed by the pyATS testbed inventory.

    Default role="managed" matches the agent boundary — i.e., excludes the
    sp-pe-* PEs that we don't manage operationally.
    """
    from nornir.core.plugins.connections import ConnectionPluginRegister
    from nornir.core.processor import Processors
    from nornir.core.state import GlobalState
    from nornir.plugins.runners import ThreadedRunner

    # Discover connection plugins from installed packages (InitNornir does this
    # automatically; since we build Nornir() directly we trigger it ourselves).
    ConnectionPluginRegister.auto_register()

    inv = build_inventory(role_filter=role)
    return Nornir(
        inventory=inv,
        runner=ThreadedRunner(num_workers=num_workers),
        processors=Processors(),
        data=GlobalState(),
    )
